---
apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: csi-s3-secret
stringData:
  accessKeyID: <in_notes>
  secretAccessKey: <in_notes>
  endpoint: https://storage.yandexcloud.net
