# helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
# helm repo update
# helm install prometheus prometheus-community/kube-prometheus-stack \
#   -n monitoring \
#   --create-namespace \
#   --set grafana.service.type=LoadBalancer
# kubectl create -f servicemonitors.yaml
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: frontend
  namespaceSelector:
    matchNames:
      - onlineboutique
  endpoints:
  - port: http
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: checkoutservice
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: checkoutservice
  namespaceSelector:
    matchNames:
      - onlineboutique
  endpoints:
  - port: http
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: productcatalogservice
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  namespaceSelector:
    matchNames:
      - onlineboutique
  endpoints:
  - port: http
    path: /metrics