{
 "title": "bokhanych-dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "adservice",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"onlineboutique\", pod=~\"adservice.*\", phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cartservice",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"onlineboutique\", pod=~\"cartservice.*\", phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "checkoutservice",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"onlineboutique\", pod=~\"checkoutservice.*\", phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "frontend",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"onlineboutique\", pod=~\"frontend.*\", phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "emailservice",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"onlineboutique\", pod=~\"emailservice.*\", phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "paymentservice",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"onlineboutique\", pod=~\"paymentservice.*\", phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "loadgenerator",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"onlineboutique\", pod=~\"loadgenerator.*\", phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "currencyservice",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"onlineboutique\", pod=~\"currencyservice.*\", phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "shippingservice",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"onlineboutique\", pod=~\"shippingservice.*\", phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "productcatalogservice",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"onlineboutique\", pod=~\"productcatalogservice.*\", phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "recommendationservice",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"onlineboutique\", pod=~\"recommendationservice.*\", phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "redis-cart",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"onlineboutique\", pod=~\"redis-cart.*\", phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}