# METALLB:  kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.8/config/manifests/metallb-native.yaml
# NGINX:    helm upgrade --install ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace ingress-nginx --create-namespace

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: node1-pool
  namespace: metallb-system
spec:
  addresses:
  - 116.203.59.201/32 # IP node1
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb-system
spec:
  ipAddressPools:
  - node1-pool