all:
  hosts:
    node1:
      ansible_host: 10.98.0.2
      ip: 10.98.0.2
      access_ip: 10.98.0.2
    node2:
      ansible_host: 10.98.0.3
      ip: 10.98.0.3
      access_ip: 10.98.0.3
    node3:
      ansible_host: 10.98.0.4
      ip: 10.98.0.4
      access_ip: 10.98.0.4
    node4:
      ansible_host: 10.98.0.5
      ip: 10.98.0.5
      access_ip: 10.98.0.5
    node5:
      ansible_host: 10.98.0.6
      ip: 10.98.0.6
      access_ip: 10.98.0.6
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
   
