{
 "title": "Online boutique",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Использование памяти (Мб)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"onlineboutique\", container!=\"\", container!=\"POD\"}) by (pod) / 1024^2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Состояние подов",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"onlineboutique\", phase=~\"Running|Pending|Failed\"}) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Использование CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"onlineboutique\", container!=\"POD\", container!=\"\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}