name: Application install
on:
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:   

      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Change version
        id: version
        run: |
          NEW_VERSION="0.${{ github.run_number }}.0"
          echo "::set-output name=new_version::$NEW_VERSION"
      
      - name: Pull, Tag and Push Docker images
        run: |
          IMAGES=(
            "currencyservice"
            "loadgenerator"
            "productcatalogservice"
            "checkoutservice"
            "shippingservice"
            "cartservice"
            "emailservice"
            "paymentservice"
            "frontend"
            "recommendationservice"
            "adservice"
          )
          NEW_TAG="${{ steps.version.outputs.new_version }}"
          for IMAGE in "${IMAGES[@]}"
          do
            ORIG_IMAGE="gcr.io/google-samples/microservices-demo/$IMAGE:v0.10.1" 
            # docker pull gcr.io/google-samples/microservices-demo/productcatalogservice    Error response from daemon: manifest for gcr.io/google-samples/microservices-demo/productcatalogservice-latest:latest not found: manifest unknown: Failed to fetch "latest"
            NEW_IMAGE="bokhanych/kubernetes-boutique:$IMAGE-$NEW_TAG"
            
            docker pull $ORIG_IMAGE
            docker tag $ORIG_IMAGE $NEW_IMAGE
            docker push $NEW_IMAGE
          done

      - name: Update Kubernetes manifests
        run: |
          NEW_TAG="${{ steps.version.outputs.new_version }}"
          sed -i "s|bokhanych/kubernetes-boutique:currencyservice-.*|bokhanych/kubernetes-boutique:currencyservice-$NEW_TAG|" "${{ github.workspace }}/application/boutique-app.yaml"
          sed -i "s|bokhanych/kubernetes-boutique:loadgenerator-.*|bokhanych/kubernetes-boutique:loadgenerator-$NEW_TAG|" "${{ github.workspace }}/application/boutique-app.yaml"
          sed -i "s|bokhanych/kubernetes-boutique:productcatalogservice-.*|bokhanych/kubernetes-boutique:productcatalogservice-$NEW_TAG|" "${{ github.workspace }}/application/boutique-app.yaml"
          sed -i "s|bokhanych/kubernetes-boutique:checkoutservice-.*|bokhanych/kubernetes-boutique:checkoutservice-$NEW_TAG|" "${{ github.workspace }}/application/boutique-app.yaml"
          sed -i "s|bokhanych/kubernetes-boutique:shippingservice-.*|bokhanych/kubernetes-boutique:shippingservice-$NEW_TAG|" "${{ github.workspace }}/application/boutique-app.yaml"
          sed -i "s|bokhanych/kubernetes-boutique:cartservice-.*|bokhanych/kubernetes-boutique:cartservice-$NEW_TAG|" "${{ github.workspace }}/application/boutique-app.yaml"
          sed -i "s|bokhanych/kubernetes-boutique:emailservice-.*|bokhanych/kubernetes-boutique:emailservice-$NEW_TAG|" "${{ github.workspace }}/application/boutique-app.yaml"
          sed -i "s|bokhanych/kubernetes-boutique:paymentservice-.*|bokhanych/kubernetes-boutique:paymentservice-$NEW_TAG|" "${{ github.workspace }}/application/boutique-app.yaml"
          sed -i "s|bokhanych/kubernetes-boutique:frontend-.*|bokhanych/kubernetes-boutique:frontend-$NEW_TAG|" "${{ github.workspace }}/application/boutique-app.yaml"
          sed -i "s|bokhanych/kubernetes-boutique:recommendationservice-.*|bokhanych/kubernetes-boutique:recommendationservice-$NEW_TAG|" "${{ github.workspace }}/application/boutique-app.yaml"
          sed -i "s|bokhanych/kubernetes-boutique:adservice-.*|bokhanych/kubernetes-boutique:adservice-$NEW_TAG|" "${{ github.workspace }}/application/boutique-app.yaml"

      - name: Commit and push if there are changes
        run: |
          git config --global user.email ${{ secrets.MY_GITHUB_USERMAIL }}
          git config --global user.name ${{ secrets.MY_GITHUB_USERNAME }}
          git add "${{ github.workspace }}/application/boutique-app.yaml"
          git commit -m "Update image tags to ${{ github.run_number }}"
          git push  