name: Get the latest images for application
on:
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:   
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Calculate new version
        id: version
        run: |
          NEW_VERSION="0.${{ github.run_number }}.0"
          echo "::set-output name=new_version::$NEW_VERSION"
      
      - name: Pull, Tag and Push Docker images
        run: |
          IMAGES=(
            "currencyservice"
            "loadgenerator"
            "productcatalogservice"
            "checkoutservice"
            "shippingservice"
            "cartservice"
            "emailservice"
            "paymentservice"
            "frontend"
            "recommendationservice"
            "adservice"
          )
          NEW_TAG="${{ steps.version.outputs.new_version }}"
          for IMAGE in "${IMAGES[@]}"
          do
            ORIG_IMAGE="gcr.io/google-samples/microservices-demo/$IMAGE:v0.10.1"
            NEW_IMAGE="bokhanych/kubernetes-boutique:$IMAGE-$NEW_TAG"
            
            docker pull $ORIG_IMAGE
            docker tag $ORIG_IMAGE $NEW_IMAGE
            docker push $NEW_IMAGE
          done