name: Get the latest images for application
on:
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:   
      
      - name: Login to Docker Hub
        uses: docker/login-action@main
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Calculate new version
        id: version
        run: |
          echo "::set-output name=new_version::$(git describe --tags --abbrev=0 | sed 's/v//; s/\.0$//; s/\([0-9]*\.[0-9]*\)\.[0-9]*/echo \1+0.1 | bc/' | xargs printf "v%.1f")"
      
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull, Tag and Push Docker images
        run: |
          IMAGES=(
            "currencyservice"
            "loadgenerator"
            "productcatalogservice"
            "checkoutservice"
            "shippingservice"
            "cartservice"
            "emailservice"
            "paymentservice"
            "frontend"
            "recommendationservice"
            "adservice"
          )
          NEW_TAG="${{ steps.version.outputs.new_version }}"
          for IMAGE in "${IMAGES[@]}"
          do
            ORIG_IMAGE="gcr.io/google-samples/microservices-demo/$IMAGE:latest"
            NEW_IMAGE="ghcr.io/${{ github.repository_owner }}/$IMAGE:$NEW_TAG"
            LATEST_IMAGE="ghcr.io/${{ github.repository_owner }}/$IMAGE:latest"
            docker pull $ORIG_IMAGE
            docker tag $ORIG_IMAGE $NEW_IMAGE
            docker tag $ORIG_IMAGE $LATEST_IMAGE
            docker push $NEW_IMAGE
            docker push $LATEST_IMAGE
          done
